api-manager:
        image: wso2/wso2am
        volumes:
                 - "~/vt-wso2-apim/wso2am-2.6.0/:/home/wso2carbon/wso2am-2.6.0/"
        #        - "~/default-wso2-conf/:/home/wso2carbon/wso2am-2.6.0/repository/conf/"
        ports:
                - "8243:8243"
                - "9443:9443"
                - "8280:8280"
        environment:
                - "PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
                - "JAVA_VERSION=jdk8u192-b12"
                - "JAVA_HOME=/opt/java/openjdk"
                - "JAVA_TOOL_OPTIONS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
                - "WSO2_SERVER_HOME=/home/wso2carbon/wso2am-2.6.0"
                - "WORKING_DIRECTORY=/home/wso2carbon"
                - "JAVA_OPTS=-Djava.util.prefs.systemRoot=/home/wso2carbon/.java -Djava.util.prefs.userRoot=/home/wso2carbon/.java/.userPrefs"
                - "-Dx5tEncoding=base64Url"
